# Generated by Django 5.2 on 2026-09-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('country', models.CharField(blank=True, max_length=128, null=True, verbose_name='کشور')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='شهر')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='نگاره شخصی')),
                ('age', models.SmallIntegerField(blank=True, null=True, verbose_name='سن')),
                ('information', models.TextField(blank=True, null=True, verbose_name='توضیحات کامل')),
                ('short_information', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='فایل رزومه')),
                ('title_skills', models.CharField(max_length=128, verbose_name='عنوان برای مهارت ها')),
                ('text_skills', models.TextField(blank=True, null=True, verbose_name='توضیحاتی درباره مهارت ها')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مدیر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
            },
        ),
    ]
