# Generated by Django 5.2 on 2026-09-16 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('edu', 'Education'), ('exp', 'Experience')], max_length=50, verbose_name='انتخاب حالت')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('place_name', models.CharField(max_length=128, verbose_name='نام')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'رزومه',
                'verbose_name_plural': 'رزومه',
                'ordering': ('-start_date', '-end_date'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='نام سرویس')),
                ('body', models.TextField(help_text='توضیح کوتاه اما مفید و تاثیرگذار', max_length=1025, verbose_name='توضیح')),
                ('icon', models.FileField(upload_to='services/icons', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='آیکون سرویس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمت',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='نام مهارت')),
                ('persent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد مهارت')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت',
                'ordering': ('-persent',),
            },
        ),
    ]
